import { expect, test } from "vitest";

import * as core from "./index.js";

// The barrel's job is to be a stable, complete list of what consumers may depend on. This test
// pins that list: adding an export means adding it here deliberately, and removing one (a
// breaking change for every consumer) cannot happen by accident during a refactor.
//
// Runtime values only — type-only exports leave nothing to inspect at runtime, and are pinned
// instead by `contracts.test.ts`, which imports them through this same entry point.
test("the barrel exports the package's public runtime surface", () => {
  expect(Object.keys(core).sort()).toEqual([
    "ACTIVE_OUTBOX_STATUSES",
    "AUDIO_ATTACHMENT_ID",
    "CAPTURE_LOCK",
    "DEFAULT_BACKOFF_BASE_MS",
    "DEFAULT_BACKOFF_CAP_MS",
    "DEFAULT_CAPABILITY_TTL_MS",
    "DEFAULT_FAKE_TRANSCRIBER_ENGINE",
    "DEFAULT_FAKE_TRANSCRIPT_TEXT",
    "DEFAULT_HEDGE_BUDGET_MS",
    "DEFAULT_HEDGE_FACTOR",
    "DEFAULT_HEDGE_FLOOR_MS",
    "DEFAULT_MIME_TYPE_PREFERENCES",
    "DEFAULT_OUTBOX_DATABASE_NAME",
    "DEFAULT_PROBE_TIMEOUT_MS",
    "DEFAULT_STABILITY_WINDOW_MS",
    "DERIVED_OUTBOX_ITEM_KEYS",
    "FINISHED_OUTBOX_STATUSES",
    "FakeExtractor",
    "FakeTranscriber",
    "MAX_CHUNK_INDEX",
    "MAX_SLICE_INDEX",
    "OUTBOX_COLLECTION_NAME",
    "OUTBOX_STATUSES",
    "Outbox",
    "PERMANENT_TRANSCRIBER_UNAVAILABLE_REASONS",
    "RECORDING_OUTBOX_STATUSES",
    "Recorder",
    "RecorderError",
    "ReviewValidationError",
    "SchemaParseError",
    "TRANSCRIBER_UNAVAILABLE_REASONS",
    "TerminalQueueError",
    "TranscriberUnavailableError",
    "acceptAnySuccess",
    "baseRecordingSchema",
    "buildFieldPath",
    "buildReviewRequest",
    "chunkName",
    "chunkPrefix",
    "compositeExtractor",
    "createConcurrentExtractor",
    "createConnectivity",
    "createRelay",
    "createSequentialExtractor",
    "decodeAudioDuration",
    "deriveInstanceIdempotencyKey",
    "enveloped",
    "errorOutcome",
    "extractedSchema",
    "fallbackExtractor",
    "firstCapable",
    "fullJitterDelay",
    "hedgeDelay",
    "hedged",
    "holdLock",
    "isChunkOf",
    "isLockFree",
    "isPermanentlyUnavailable",
    "isSpanGrounded",
    "isTransientFailure",
    "negotiateMimeType",
    "openCaptureSession",
    "openOutbox",
    "openOutboxDatabase",
    "outboxDocumentSchema",
    "outboxItemSchema",
    "outboxRxSchema",
    "parseFieldPath",
    "raceExtractor",
    "recordingSchema",
    "recoverInterrupted",
    "removeOutboxDatabase",
    "resolveReview",
    "resultOutcome",
    "reviewOutcomeSchema",
    "sliceOversized",
    "stripOptionalNullable",
    "summarizeWork",
    "terminalFallsThrough",
    "toExtractStep",
    "toInstanceWriteStep",
    "toWriteStep",
    "transcriptSchema",
    "workSafety",
  ]);
});
