// GENERATED by `pnpm target:refresh` — do not edit by hand.
//
// Query:        baseline widely available
// Resolved:     2026-08-04
// browserslist: 4.28.7
// caniuse-lite: 1.0.30001806
//
// This is the SYNTAX floor handed to tsdown, and it is deliberately LOWER than
// the support matrix in docs/implementation/10-build-and-packaging.md §2.1. The
// error directions are not symmetric: a floor below real support only costs bytes
// through extra downleveling, while a floor above it breaks a supported device we
// cannot hot-fix. See the R1 design spec §3.3.

/** Oxc-style target tokens. Typed `string[]` for assignability to tsdown's `target`. */
export const BROWSER_TARGET: string[] = [
  "chrome121",
  "edge121",
  "firefox122",
  "ios17.2",
  "safari17.2",
];
