// GENERATED by `pnpm snugg:refresh` — do not edit by hand.
//
// Source:    https://app.snuggpro.com/apidocs/swagger.json
// Refreshed: 2026-08-10
// Leaves:    51
//
// The vendor's own description for each field we extract — the same sentence a Snugg Pro
// user reads in their UI. `schema.ts` composes this with our own note, where we have one,
// so the model gets both the definition and the prohibition that matters for extraction.
//
// `pnpm snugg:check` fails when this no longer matches the live spec. Regeneration is
// deliberate rather than automatic, so a vendor rewording lands in a reviewable diff
// instead of silently changing what an extraction model is told.

/** Vendor descriptions, keyed by the leaf name as it appears in `snuggValuesSchema`. */
export const VENDOR_DESCRIPTIONS: Readonly<Record<string, string>> = {
  atticHasKneeWall: "Choose Yes if there is a knee wall in this attic space.",
  atticInsulation:
    'Enter the total R-value of insulation installed (BASE) or to be installed (IMPROVED) in this Attic. Framing factors have already been taken into account, so specify the R-value of the insulation within the cavity. **Note:** Edit Base fields in the Details section only if you\'re confident of the actual value that is entered. The modeling engine utilizes utility data and input form data to determine the "effective" values on the Base side. Edit Improved fields in the Details section with the details of what you recommend be installed in the house. These values are only used if the item is Recommended. Default values are supplied by the modeling engine, but can be overridden.',
  atticInsulationDepth:
    "Enter the depth of all installed attic or ceiling insulation. If the insulation is not evenly distributed, estimate an average depth for the area. If the insulation is evenly distributed but has different depths installed in different area, use the depth of insulation that covers the largest area. If there is no attic and instead vaulted ceilings, enter an estimate of the thickness of insulation in the vaulted cavity.",
  atticInsulationType:
    "Select the type of insulation that is installed in the attic or ceiling. If more than one type of insulation is installed, select the type that covers that largest area.",
  atticRoofType: "Select the type of roofing material for this roof section.",
  blowerDoorReading:
    "The baseline airflow, in cubic feet per minute, through leaks in the building when there is a pressure difference between the building and ambient of 50 Pascals. This is the result of your blower door test if you perform one. If you do not enter a number here, the software will determine an appropriate number based on the age and size of the home. On the improved side, the default recommendation is a 25% reduction in the air leakage. You may of course override this to whatever number you feel you'll be able to achieve.",
  blowerDoorTestPerformed:
    'Choose "Tested" if an actual blower door test was performed. Choose "Estimate" if the blower door reading below is an estimate.',
  conditionedArea:
    'Enter the total area of the home that is heated or air conditioned. This may be different from the typical measure of the size of the home, especially if you have a heated garage or similar area of the home that receives heating or air conditioning. Make sure to include any space of the home that has heating or air conditioning, including conditioned basements (unless you mark the next field "Area Includes Basement" as No).',
  dhwAge:
    "Select the age in years of the hot water system that stores or delivers the domestic hot water for the home. If more than one type of system is used for hot water in the home, select the age for the one that delivers the most gallons of hot water to the home.",
  dhwFuel2:
    "Select the type of energy source used to provide domestic hot water for the home. Domestic hot water is typically the hot water that comes from the faucets, showers, bathtubs, washing machines and dishwashers in the home. If more than one type of energy source is used to provide hot water, select the type that provides the most gallons of hot water.",
  dhwLocation:
    "Select the where the hot water system that stores or delivers the domestic hot water for the home is located. If more than one type of system is used for hot water in the home, select the location for the one that delivers the most gallons of hot water to the home.",
  dhwManufacturer: "Enter the Manufacturer of the water heater.",
  dhwTankSize: "Enter the tank size the water heater in gallons.",
  dhwType2: "Enter the type of water heater installed (BASE) or to be installed (IMPROVED).",
  floorsAboveGrade:
    "Select the number of stories for the living area of this home, not counting any basement or walkout as a story. If this home is in a multi-story, multi-family complex, report only those stories in the living area of this particular home, which could likely be less than the total number of stories of the building.",
  healthAmbientCarbonMonoxide:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthAsbestos:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthDraftPressure:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthElectrical:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthGasLeak:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthLead:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthMoldMoisture:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthNaturalConditionSpillage:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthRadon:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthRoofCondition:
    "Choose the appropriate description to describe the condition of the roof. If the roof is in good condition, choose “Good”, if it has potential issues, choose “Potential Issues”. If you did not perform this test and do not want the test information to show up on the homeowner report, then choose “NA”",
  healthUndilutedFlueCo:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthVenting:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthWorstCaseDepressurization:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  healthWorstCaseSpillage:
    'Choose the appropriate description for this test. If you performed an actual test and it passed, then choose "Passed", if the test failed, then choose "Failed". If you did not perform this test, but suspect there might be issues or have notes to provide the homeowner or contractor, then choose "Warning". If you did not perform this test and do not want the test information to show up on the homeowner report, then choose "Not Tested".',
  hvacCoolingCapacity:
    "Enter the output capacity of the cooling equipment in (Btu/hr). Reminder: cooling systems are often rated in tons. 1 ton = 12,000 Btu/hr. **NOTE:** This has changed since v3 of Snugg Pro. v4 and later requires the number be in Btu/hr, not kBtu/hr. All v3 jobs that were migrated to v4 have been converted to the proper number by multiplying it by 1000.",
  hvacDuctInsulation:
    "Select the type of insulation installed over the duct work for this system. Note: If ducts are covered wholly or partially by incidental insulation present in the cavity in which they are installed, then select the insulation type that most closely matches the average R-value of the insulation. If you know the actual duct insulation R-value, choose Measured (R-Value) and enter the data in the field below.",
  hvacDuctLeakage:
    "Choose the estimated leakage to the outside through the duct system as a percentage of the total air handler flow. If you actually performed a duct blaster test, choose Measured (CFM25) and enter a value in the field below.",
  hvacDuctLeakageValue:
    "If you perform a duct blaster test, please enter the tested leakage to outside at 25 Pa per RESNET Standard Section 803.7.",
  hvacDuctLocation: "Select the location of the duct work for this system.",
  hvacHeatingCapacity:
    "Enter the output capacity of the heating equipment in (Btu/hr). **NOTE:** This has changed since v3 of Snugg Pro. v4 and later requires the number be in Btu/hr, not kBtu/hr. All v3 jobs that were migrated to v4 have been converted to the proper number by multiplying it by 1000.",
  hvacHeatingEnergySource:
    "This is the primary fuel source. It is used to set prices and energy content.",
  hvacHeatingSystemManufacturer: "Enter the Manufacturer of the Heating Equipment.",
  hvacHeatingSystemModel:
    "Enter the Model # of the Heating Equipment. **Pro-tip**: Always capture an image of the nameplate on the existing equipment and store it in the photos section for future reference.",
  hvacHeatingSystemModelYear: "Enter the Year the Heating Equipment was built.",
  hvacSystemEquipmentType:
    "Select which type of HVAC system you'd like to describe. This list shows every possible type of heating or cooling system (or combination thereof) that is available in our software. Pay attention to the “shared ducts” vs. “standalone ducts” component. Note: this is very similar to the “Both” option that was available in version 4.",
  hvacUpgradeAction:
    "Choose an action that you plan to take for this HVAC system.**Replace with a newer model:** Replace the existing equipment with a new version of the same thing. Eg. replace a 78 AFUE furnace with a new 98 AFUE furnace **Keep an existing system as is:** Do nothing to a system or just change the percent of total load that that old system covers in the house. **Remove a system permanently:** Rip out an entire system and replace it with something completely new, like going from a direct heater and room AC to a central heat pump. In this instance you will have a system that is described on the base side, and the improved side will be blank. **Install a new non-existing system:** A brand new system that replaces the system that was removed when you chose: Remove a system permanently.",
  numberOfBedrooms:
    '2005 RESNET Standards define a bedroom as: A room or space 70 square feet or greater, with egress window and closet, used or intended to be used for sleeping. A "den", "library", "home office" with a closet, egress window, and 70 square feet or greater or other similar rooms shall count as a bedroom, but living rooms and foyers shall not.',
  typeOfHome:
    "Select the type of home that most closely resembles this home. Single-family Attached would be a duplex or a townhome with shared walls. **Please note:** that only multi-family units with independently metered fuel and electricity can be modeled with this software.",
  wallCavityInsulation:
    'Enter the total R-value of insulation installed (BASE) or to be installed (IMPROVED) in this Wall System. **Note:** Edit Base fields in the Details section only if you\'re confident of the actual value that is entered. The modeling engine utilizes utility data and input form data to determine the "effective" values on the Base side. Edit Improved fields in the Details section with the details of what you recommend be installed in the house. These values are only used if the item is Recommended. Default values are supplied by the modeling engine, but can be overridden.',
  wallCavityInsulationType:
    "Select the type of insulation that is installed in the wall cavity. If more than one type of insulation is installed, select the type that covers that largest area.",
  wallExteriorWallSiding:
    "Select the type of exterior finish material that covers the outside of this home.",
  wallsInsulated:
    "Is there insulation in the wall cavities of this home? If so, how good is it? If unsure, please leave blank. **Well**: All cavities contain insulation at full or near full depth with gaps and voids not exceeding 5%. **Poor**: Majority of cavities contain insulation, but one or more of the following is suspected: low density, low depth, poor installation. **Yes**: You can confirm that insulation exists, but are unsure of the installation quality. **No** - No insulation value is applied to cavities.",
  windowEnergyStar: "Select Yes if this window system is ENERGY STAR Certified.",
  windowFrame:
    "Select the type of window frame material that is used for the windows installed in the home. If more than one type of window is installed, add a second window system.",
  windowType:
    "Select the type of windows that are installed in the home. If more than one type of window is installed, add a second window system.",
  yearBuilt:
    'Enter the year the home or building was constructed. If there was a major addition made to the home, the "Year built" should be entered as the year the majority of the area that is heated and air conditioned was built.',
};
