#!/usr/bin/env node
/**
 * @file Regenerates packages/build-config/src/target.generated.ts.
 *
 * Run with `pnpm target:refresh`. Deliberately NOT run by check.sh or CI:
 * regenerating is an intentional act, like `update-browserslist-db`, so the
 * published syntax floor lands in a reviewable diff instead of drifting with the
 * lockfile's caniuse-lite. See the R1 design spec §3.
 *
 * This file stays thin on purpose. All the real logic lives in the typechecked,
 * unit-tested `toOxcTargets`; nothing under scripts/ is covered by a tsconfig.
 *
 * It imports that module with an explicit `.ts` specifier because Node 24 strips
 * types natively but does no extension substitution — `./target.js` would not
 * exist on disk. The module is plain types-and-functions, so stripping applies
 * cleanly.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

import browserslist from "browserslist";

import { toOxcTargets } from "../packages/build-config/src/target.ts";

/**
 * Baseline "widely available" — a feature set every major browser has supported
 * for 30 months. Chosen over tsdown's own `baseline-widely-available` token
 * because that token expands to a snapshot hardcoded in tsdown (and, identically,
 * in Vite) which was roughly ten Chrome majors stale. See the design spec §3.1.
 */
const QUERY = "baseline widely available";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outFile = path.join(repoRoot, "packages/build-config/src/target.generated.ts");

const require = createRequire(import.meta.url);
// caniuse-lite is browserslist's own direct dependency, so resolve it THROUGH
// browserslist. Resolving it from the repo root fails under pnpm's strict layout,
// where only declared dependencies are visible.
const browserslistPkgPath = require.resolve("browserslist/package.json");
const browserslistVersion = require(browserslistPkgPath).version;
const caniuseVersion = createRequire(browserslistPkgPath)("caniuse-lite/package.json").version;

const targets = toOxcTargets(browserslist(QUERY));

if (targets.length === 0) {
  throw new Error(
    `browserslist("${QUERY}") produced no oxc-mappable targets. Refusing to write an empty floor.`,
  );
}

const resolvedOn = new Date().toISOString().slice(0, 10);

const contents = `// GENERATED by \`pnpm target:refresh\` — do not edit by hand.
//
// Query:        ${QUERY}
// Resolved:     ${resolvedOn}
// browserslist: ${browserslistVersion}
// caniuse-lite: ${caniuseVersion}
//
// This is the SYNTAX floor handed to tsdown, and it is deliberately LOWER than
// the support matrix in docs/implementation/10-build-and-packaging.md §2.1. The
// error directions are not symmetric: a floor below real support only costs bytes
// through extra downleveling, while a floor above it breaks a supported device we
// cannot hot-fix. See the R1 design spec §3.3.

/** Oxc-style target tokens. Typed \`string[]\` for assignability to tsdown's \`target\`. */
export const BROWSER_TARGET: string[] = ${JSON.stringify(targets, null, 2)};
`;

writeFileSync(outFile, contents, "utf8");

// Prettier owns formatting and format:check is a check.sh stage, so normalize the
// generated file rather than hand-matching the repo's style in a template string.
execFileSync("pnpm", ["prettier", "--write", path.relative(repoRoot, outFile)], {
  cwd: repoRoot,
  stdio: "inherit",
});

console.log(`target:refresh -> ${targets.join(", ")}`);
